DROP TABLE IF EXISTS REVINFO;

CREATE TABLE REVINFO (
    REV integer generated by default as identity (start with 1),
    REVTSTMP bigint,
    primary key (REV)
);

CREATE SEQUENCE hibernate_sequence;

